/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Developer Tools",
  "description": "Adds new menu options to the editor: copy/paste blocks, make space, and more!",
  "credits": [
    {
      "name": "griffpatch"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "recommended"
  ],
  "enabledByDefault": true
};
export default manifest;
